### ISSUE TITLE
Er is flink meer functionaliteit gewenst rondom de gebruikers

### ISSUE THREAD

**Issue by ekempnl** [tcoenraad/wat-een-les#102]
Dit is redelijk veel functionaliteit die nog erbij kan komen. Hier een lijst:

1. Je wil kunnen zien wie een les heeft aangemaakt
2. Je wil kunnen zien wat voor iemand dat is (zie 3.)
3. Je wil informatie over jezelf toe kunnen voegen aan je profiel (vak, jaren lesgegeven, school, foto, over mij-beschrijving)
4. Als je op een gebruiker klikt bij een les, wil je naar zijn profiel gaan, zodat je kunt zien welke lessen die docent nog meer heeft toegevoegd.

**Comment by jipspel** [comment]
1) fixed in 60e38d9a31a1275283095ef23c91b024a50540d2
