### ISSUE TITLE
Benaming van menu-onderdelen (en dus pagina's) is verwarrend

### ISSUE THREAD

**Issue by ekempnl** [tcoenraad/wat-een-les#103]
Docenten verwachten een overzichtspagina (mijn lessen, mijn favorieten), een profielpagina (over mij, informatie etc.), en een tab accountgegevens (huidige 'gegevens aanpassen').

**Comment by jipspel** [comment]
Profielpagina gaat later misschien komen, ik ga nu eerst de huidige site functioneel maken, mocht er tijd over zijn dan is de uitbreiding van een profielpagina uiteraard mogelijk
