### ISSUE TITLE
Stemmen zijn niet erg transparant en kunnen een vertekend beeld geven

### ISSUE THREAD

**Issue by ekempnl** [tcoenraad/wat-een-les#109]
Gebruikers geven aan dat je wilt kunnen zien wat voor stemmen er gegeven zijn. (Bijvoorbeeld om ook uitschieters te herkennen). Hierbij werd ook geopperd om te laten zien wie gestemd had, en eventueel met uitleg (zoals bij een review-systeem).

Daarnaast is het misschien een goed idee om pas vanaf 5 of 10 stemmen de rating zichtbaar te maken, zodat een enkeling geen vertekend beeld kan geven van de kwaliteit van de les.

**Comment by jipspel** [comment]
Review systeem/wie gestemd heeft gaan we niet doen. Ook manier van stemmen laten we niet zien, zou eventueel in eigen overzicht kunnen.
