### ISSUE TITLE
De vorm waarin lessen op de website kunnen worden geplaats is misschien niet duidelijk voor docenten

### ISSUE THREAD

**Issue by ekempnl** [tcoenraad/wat-een-les#117]
We kunnen bij het aanmaken van lessen, naast 'Lesbeschrijving' een vraagtekentje plaatsen.
Als ze daarop hun muis houden kunnen we ze uitleggen waarom we willen dat een complete les op de website geplaatst wordt, in plaats van dat er een document wordt toegevoegd. Voor bijvoorbeeld een powerpoint presentatie zal er wellicht een tip bij moeten staan dat je die ergens anders moet uploaden (Drive, Dropbox of Scribd (https://www.scribd.com/upload-document) )

**Comment by tcoenraad** [comment]
Gefikst in d7e754406e86db8fc8daaba3ae3b32a79e04507a
