### ISSUE TITLE
Add pages

### ISSUE THREAD

**Issue by evavandeneijnden** [tcoenraad/wat-een-les#14]
Dit kunnen voor nu gewoon dummypagina's zijn, maar testers moeten er op kunnen klikken.
- [ ] Over het team
- [ ] Veelgestelde vragen
- [ ] Contact

**Comment by ekempnl** [comment]
Als static pagina's aangemaakt, nu nog met de link: /static/faq etc.
Misschien in de toekomst static in url weghalen
