### ISSUE TITLE
Zoekquery verwijderen

### ISSUE THREAD

**Issue by tcoenraad** [tcoenraad/wat-een-les#19]
Als je een zoekopdracht doet moet je die kunnen verwijderen. Er is nu een lelijk knopje 'Alle lessen' voor, maar dat is dus lelijk.

**Comment by jipspel** [comment]
Wordt gratis meegeleverd met searchkick, dus slechts toevoeging van paar regeltjes code

**Comment by jipspel** [comment]
Closed in #43
