### ISSUE TITLE
Login redirects to homepage, not "current" page

### ISSUE THREAD

**Issue by evavandeneijnden** [tcoenraad/wat-een-les#38]

**Comment by tcoenraad** [comment]
https://github.com/plataformatec/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update

**Comment by jipspel** [comment]
Voor uitloggen moeten we even kijken waar we naar willen linken

**Comment by tcoenraad** [comment]
'This wiki page is fairly out-of-date, just read the code: lib/devise/controllers/store_location.rb'

Ik denk dat je nog ietsje anders moet.
