### ISSUE TITLE
Lesson accepts negative preparation_time

### ISSUE THREAD

**Issue by evavandeneijnden** [tcoenraad/wat-een-les#66]
There is no check in lesson.rb that checks whether the user-provided preparation_time is a positive number.

**Comment by jipspel** [comment]
Ik denk dat je als je tijd hebt deze zelf kan oplossen, hij is namelijk heel triviaal, maar als je het te druk hebt moet je het even zeggen :)

**Comment by evavandeneijnden** [comment]
Ga ik doen! Had dit al even met Twan overlegd, maar ik dacht dat jullie het vervelend zouden vinden als ik het zomaar ging doen, dus had maar even zo gedaan. Maar nu ga ik het gewoon even zelf regelen ^^

**Comment by jipspel** [comment]
Fixed in 842de996ac7c21fd1ed8d7c5ab81189f1558b1b8
