### ISSUE TITLE
Login en sign up pagina zijn nog in oude stijl

### ISSUE THREAD

**Issue by ekempnl** [tcoenraad/wat-een-les#75]
Deze moeten ook in de stijl van de les aanmaken en gegevens wijzigen pagina's, dus met horizontal forms.

Extra: Op de sign-up pagina staat 'Minimaal8 karakters' aan elkaar. Hiervan maken: '(minimaal 8 karakters)'

**Comment by tcoenraad** [comment]
Gefikst in 05a8fc9fe44b32857270e9a75e1ef441c39f8157.
