### ISSUE TITLE
Manier van zoeken veranderen, zoals op Pinterest

### ISSUE THREAD

**Issue by ekempnl** [tcoenraad/wat-een-les#78]
Omdat het zoeken nu onnatuurlijk aanvoelt, en je geen manier hebt om binnen je zoekopdracht te filteren, lijkt het handig om de manier van zoeken van Pinterest over te nemen. Dus dat de woorden die je typt omgezet worden in labels.

Als je op een tag klikt (in Tips of bij een les zelf), zou er dan ook een label bij moeten komen, ipv dat de oude weggaat. Je kunt zelf met een kruisje makkelijk weer een zoeklabel weghalen.

Hieronder hoe het er idealiter uit zou komen te zien (net als op Pinterest):

![pinterestlabels](https://cloud.githubusercontent.com/assets/4570036/7910224/0edc0f96-0853-11e5-9413-5f67a1d8b4a4.PNG)

**Comment by tcoenraad** [comment]
Als we dit willen moeten we de autocomplete opgeven, het kost te veel werk om dit beide te krijgen

**Comment by ekempnl** [comment]
Ja dit is wel een belangrijke, dus zou ik wel doen :P

--- Oorspronkelijk bericht ---

Van: "Twan Coenraad" <notifications@github.com>
Verzonden: 15 juni 2015 23:11
Aan: "tcoenraad/wat-een-les" <wat-een-les@noreply.github.com>
CC: "ekempnl" <e.kemp@student.utwente.nl>
Onderwerp: Re: [wat-een-les] Manier van zoeken veranderen, zoals op Pinterest (#78)

Als we dit willen moeten we de autocomplete opgeven, het kost te veel werk om dit beide te krijgen

---

**Comment by jipspel** [comment]
Wat bedoel je daar mee :P ? autocomplete droppen of pinterestidee droppen?

**Comment by ekempnl** [comment]
Ik zou autocomplete dan droppen als er echt één moet.Maar bijvoorbeeld Selectize heeft ook labels, en die heeft ook aanvulfuncties. Misschien is dat dan nog een future work-issue, maar ik denk dat die Pinterest-achtige labels echt heel goed zijn voor de zoekfunctie op de website. En dan dus dat als je op een label ergens bij een les klikt (of links in 'verfijn je zoekopdracht') hij erbij komt, zodat het echt als een heerlijk handig filter werkt.

Vriendelijke groeten,
Erik Kemp

Date: Tue, 16 Jun 2015 03:03:54 -0700

**Comment by jipspel** [comment]
okay

**Comment by tcoenraad** [comment]
Van Eva hebben we begrepen dat het er voornamelijk om ging dat je bij het klikken op een tag de selectie verkleint. Dat hebben we uitgeprobeerd, maar de tags geven ons meer de indruk dat je een nieuwe zoekopdracht doet, dan 'm verkleint.

**Comment by ekempnl** [comment]
Docenten vonden dat juist niet, en leek het handig als je een label erbij kreeg, met dan ook zo'n kruisje net zoals bij selectize zodat je het eventueel ook weer weg kunt halen. Dan werk je dus met een filter, en kun je dat wat eerst 'Tips' heette, ook verfijn je zoekopdracht noemen.

Vriendelijke groeten,
Erik Kemp

Date: Thu, 18 Jun 2015 00:52:45 -0700
