### ISSUE TITLE
Het is niet mogelijk om een document toe te voegen aan een les

### ISSUE THREAD

**Issue by evavandeneijnden** [tcoenraad/wat-een-les#85]
Gebruikers willen dit wel heel graag. We kunnen dit mogelijk maken, of als dat niet gewenst is duidelijk aangeven dat men documenten elders kan hosten (wellicht met een voorbeeld van waar dat kan!)

**Comment by jipspel** [comment]
Dit kan opgelost worden door dingen in drive/dropbox te zetten en dan het linkje toe te voegen
