### ISSUE TITLE
Bij het aanmaken van een les is de tekst "materiaalsoort" verwarrend

### ISSUE THREAD

**Issue by evavandeneijnden** [tcoenraad/wat-een-les#86]
Docenten zouden dit liever vervangen door bijvoorbeeld "lesmateriaal", of liever nog opsplitsen in "werkvorm" en "lesmateriaal".

**Comment by jipspel** [comment]
Voor nu wordt het vervangen door lesmateriaal, in de toekomst zou je hier werkvorm aan toe kunnen voegen
