### ISSUE TITLE
Er wordt weinig informatie gegeven over de eigen lessen

### ISSUE THREAD

**Issue by evavandeneijnden** [tcoenraad/wat-een-les#90]
Docenten zouden leuk vinden om bijv. te zien hoe veel mensen de les die ze hebben geupoad als favoriet hebben, of bijvoorbeeld hoe veel reacties er zijn/hoe de rating is.

Hier een screenshot van hoe het bij Kahoot wordt gedaan. Je ziet daar hoe vaak je les gegeven is, hoeveel mensen hem als favoriet hebben:

![kahootlessoninfo](https://cloud.githubusercontent.com/assets/4570036/7930971/201eb74e-090d-11e5-9271-c5be4d716e58.PNG)

**Comment by jipspel** [comment]
Fixed in 7822cd63e84c96a94f2d274d50e0163939d88fbc
